apiVersion: v1
kind: Service
metadata:
  name: ach-router-service
spec:
  type: ClusterIP
  selector:
    component: ach-router-service
  ports:
    - port: 10000
      targetPort: 80
      name: http-ach-router-service